pool: Azure Pipelines

pr: none

trigger:
  branches:
    include:
    - main
    - features/*
  paths:
    include:
    - src/Core/*
    - src/ConsoleTest/*  

stages:
- stage: Echo1
  jobs:
  - deployment: Echo1
    displayName: Echo1
    environment: dev
    strategy: 
      runOnce:
        deploy:
          steps:
          - bash: echo ConsoleTest1 $(Build.SourceBranch)
          # - task: FileTransform@1
          #   displayName: 'File transformation: appsettings.json'
          #   inputs:
          #     folderPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          #     targetFiles: '**/template.json'
          #     fileType: json

- stage: Echo2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: Echo2
    steps:
    - bash: echo ConsoleTest2
